name: carpooling_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  flutter_bloc: ^9.1.1
  firebase_auth: ^6.0.0
  geolocator: ^14.0.2
  cloud_firestore: ^6.0.0
  mapbox_maps_flutter: ^2.10.0
  permission_handler: ^11.0.1
  flutter_dotenv: ^6.0.0
  http: ^1.5.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1
  googleapis_auth: ^2.0.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0
  page_transition: ^2.0.9
  flutter_rating_bar: ^4.0.1
  iconsax: ^0.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/