// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzx4y-tu2TSUE_Uw3Ag72TLV5Lxf5rHIk',
    appId: '1:332548050555:web:879b1d9c276d9aadd09cde',
    messagingSenderId: '332548050555',
    projectId: 'carpooling-app-5ae7c',
    authDomain: 'carpooling-app-5ae7c.firebaseapp.com',
    storageBucket: 'carpooling-app-5ae7c.firebasestorage.app',
    measurementId: 'G-H5VJT10571',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3GnBchPZPjN2L7omEaEgmtpM0ngr6jP8',
    appId: '1:332548050555:android:a0ab94452232b5aed09cde',
    messagingSenderId: '332548050555',
    projectId: 'carpooling-app-5ae7c',
    storageBucket: 'carpooling-app-5ae7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeBucbZRnKelawvcWNDH07FpBbiH16OX0',
    appId: '1:332548050555:ios:3f3246571477972ad09cde',
    messagingSenderId: '332548050555',
    projectId: 'carpooling-app-5ae7c',
    storageBucket: 'carpooling-app-5ae7c.firebasestorage.app',
    iosBundleId: 'com.example.carpoolingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeBucbZRnKelawvcWNDH07FpBbiH16OX0',
    appId: '1:332548050555:ios:3f3246571477972ad09cde',
    messagingSenderId: '332548050555',
    projectId: 'carpooling-app-5ae7c',
    storageBucket: 'carpooling-app-5ae7c.firebasestorage.app',
    iosBundleId: 'com.example.carpoolingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzx4y-tu2TSUE_Uw3Ag72TLV5Lxf5rHIk',
    appId: '1:332548050555:web:c762d6a01197fc1fd09cde',
    messagingSenderId: '332548050555',
    projectId: 'carpooling-app-5ae7c',
    authDomain: 'carpooling-app-5ae7c.firebaseapp.com',
    storageBucket: 'carpooling-app-5ae7c.firebasestorage.app',
    measurementId: 'G-JDME5Q535X',
  );
}
